### ISSUE TITLE
Change error message wrapper

### ISSUE THREAD

**Issue by jevets** [realripley00/bootstrap-form#2]
BS4 uses `.invalid-feedback` for error messages, not the `.help-block`.

Change the wrapper `$format` variable to something like this, right here:
https://github.com/realripley00/bootstrap-form/blob/master/src/BootstrapForm.php#L1034

Currently:

```php
protected function getFieldError($field, $format = '<span class="help-block">:message</span>')
{
    //
}
```

Proposed new:

```php
protected function getFieldError($field, $format = '<div class="invalid-feedback">:message</div>')
{
    //
}
```

**Comment by realripley00** [comment]
Updated on 1.1.20
