### ISSUE TITLE
Not showing input validation errors when using input addons

### ISSUE THREAD

**Issue by RobHawk90** [realripley00/bootstrap-form#9]
I've noticed that when I use a "suffix" or "prefix" options on inputs, for some reason, the validation errors don't show up, only the input's borders change to red:
```
{{ BootForm::open(['id' => 'income-tax-form', 'model' => $incomeTax, 'store' => 'IncomeTaxController@store', 'update' => 'IncomeTaxController@update']) }}

<div class="row">
    <div class="col-md-4">
        {!! 
            BootForm::text(
                'min_income',
                __('income_taxes.labels.min_income'),
                null,
                [
                    'class' => 'currency-mask',
                    //'prefix' => '<div class="input-group-prepend"><span class="input-group-text">R$</span></div>',
                ]
            )
        !!}
    </div>

    <div class="col-md-4">
        {!! 
            BootForm::text(
                'aliquot',
                __('income_taxes.labels.aliquot'),
                null,
                [
                    'class' => 'percent-mask',
                    //'suffix' => BootForm::addonIcon('fa fa-percent'),
                ]
            )
        !!}
    </div>

    <div class="col-md-4">
        {!! 
            BootForm::text(
                'deduction',
                __('income_taxes.labels.deduction'),
                null,
                [
                    'class' => 'currency-mask',
                    'prefix' => '<div class="input-group-prepend"><span class="input-group-text">R$</span></div>',
                ]
            )
        !!}
    </div>

    <div class="col-md-4">
        {!! 
            BootForm::text(
                'deduction_per_dependent',
                __('income_taxes.labels.deduction_per_dependent'),
                null,
                [
                    'class' => 'currency-mask',
                    'prefix' => '<div class="input-group-prepend"><span class="input-group-text">R$</span></div>',
                ]
            ) 
        !!}
    </div>
</div>

{!! BootForm::submit(__('income_taxes.labels.submit')) !!}

{{ BootForm::close() }}
```
![image](https://user-images.githubusercontent.com/5470472/49014140-3a304400-f166-11e8-9a74-a4930db61290.png)

**Comment by realripley00** [comment]
I've notice this as well and I find it pretty frustrating. It's actually an issue with Bootstrap 4, not specific to this package. This specifically is why I've chosen to stick with Bootstrap 3 on at least one project.

Take a look at this issue in Bootstrap 4's repo.

https://github.com/twbs/bootstrap/issues/23454

My solution so far has been to avoid prefixes and suffixes on inputs that require validation if at all possible. If that's not possible, you can override BS4 default input-group/validation layout doing something along these lines:


.form-group {
  &.was-validated {
    &.is-invalid {
      background-color: #ffe9e6;
      label {
        color: #dc3545;
      }
      **.invalid-feedback {
        display: block;
      }**
    }
  }
}

**Comment by RobHawk90** [comment]
> I've notice this as well and I find it pretty frustrating. It's actually an issue with Bootstrap 4, not specific to this package. This specifically is why I've chosen to stick with Bootstrap 3 on at least one project.
> 
> Take a look at this issue in Bootstrap 4's repo.
> 
> [twbs/bootstrap#23454](https://github.com/twbs/bootstrap/issues/23454)
> 
> My solution so far has been to avoid prefixes and suffixes on inputs that require validation if at all possible. If that's not possible, you can override BS4 default input-group/validation layout doing something along these lines:
> 
> .form-group {
> &.was-validated {
> &.is-invalid {
> background-color: #ffe9e6;
> label {
> color: #dc3545;
> }
> **.invalid-feedback { display: block; }**
> }
> }
> }

OK, I'll check that, thanks!
